# Generated by Django 4.0.1 on 2022-01-20 15:35

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to=users.utils.user_directory_path),
        ),
    ]
