# Generated by Django 4.0.1 on 2022-01-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_book_cover_bookimage_book_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
    ]
