# Generated by Django 4.0.1 on 2022-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_book_slug_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
