# Generated by Django 4.0.1 on 2022-01-31 20:00

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_author_slug_alter_publisher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.utils.author_directory_path),
        ),
    ]
