# Generated by Django 4.0.1 on 2022-01-31 21:12

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='authors/default.png', null=True, upload_to=products.utils.author_directory_path),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(default='books/default.png', upload_to=products.utils.book_directory_path),
        ),
    ]
